### ISSUE TITLE
报错，无法显示

### ISSUE THREAD

**Issue by re-ovo** [ddmy/vue-gantt#11]
按照例子写了下，无法正常显示，控制台报错：
```
[Vue warn]: useCssVars is called without current active component instance.
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
[Vue warn]: Invalid VNode type: Symbol(Fragment) (symbol) 
  at <Gantt data= [{…}] dateRangeList= (2) ['2022-01-01', '2022-03-05'] itemText="游戏/项目"  ... > 
  at <Space vertical="" > 
  at <OverviewView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <LayoutContent style= {padding: '8px'} > 
  at <Layout has-sider="" position="absolute" style= {top: '64px'} > 
  at <Layout position="absolute" > 
  at <DashboardView onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <RootNavView> 
  at <LoadingBarProvider> 
  at <NotificationProvider> 
  at <MessageProvider> 
  at <DialogProvider> 
  at <ConfigProvider theme= {name: 'light', common: {…}, Alert: {…}, Anchor: {…}, AutoComplete: {…}, …} locale= {name: 'zh-CN', global: {…}, Popconfirm: {…}, Cascader: {…}, Time: {…}, …} > 
  at <App>
```

我的代码:
```js
<script setup>
import Gantt from 'vue3-gantt'
import 'vue3-gantt/dist/style.css'
const dateRangeList = ref(['2022-01-01', '2022-03-05'])
const data = ref([
  {
    type: "normal",
    color: "",
    name: "流星蝴蝶剑",
    schedule: [
      {
        id: 222221,
        name: "小年活动",
        desc:
            "这个活动很重要，6666666营收数百万，跨部门合作的一个大项目，BOSS亲自下场坐镇指挥，大家一定要团结一心!",
        backgroundColor: "#482",
        textColor: "#fff",
        days: ["2022-04-04", "2022-04-04"],
      },
    ],
  },
]);
</script>
```
```html
<template>
<Gantt
        :data="data"
        :dateRangeList="dateRangeList"
        itemText="游戏/项目"
        dateText="日期"
    />
</template>
```

**Comment by ddmy** [comment]
这个问题是最近更新版本后出现的，我这边尽快处理

**Comment by ddmy** [comment]
@re-ovo  真实奇怪，这个问题我本地复现了N多次，今天换了网络环境突然好了。

问题存在期间，我调试发现打包后的代码，是 setup方法中 onMounted 没有执行。

**Comment by ddmy** [comment]
> @re-ovo  真实奇怪，这个问题我本地复现了N多次，今天换了网络环境突然好了。
> 
> 
> 
> 问题存在期间，我调试发现打包后的代码，是 setup方法中 onMounted 没有执行。

@re-ovo 如果你还能复现，能否提供一个demo看下

**Comment by re-ovo** [comment]
`import 'vue3-gantt/dist/style.css'`这个又报错了

```
3:06:44 PM [vite] Internal server error: Missing "./dist/style.css" export in "vue3-gantt" package
  Plugin: vite:import-analysis
  File: /Users/re/IdeaProjects/first-it/frontend/src/views/dashboard/OverviewView.vue
      at bail (file:///Users/re/IdeaProjects/first-it/frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:32678:8)
      at resolve (file:///Users/re/IdeaProjects/first-it/frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:32755:10)
      at resolveExports (file:///Users/re/IdeaProjects/first-it/frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:34135:12)
      at resolveDeepImport (file:///Users/re/IdeaProjects/first-it/frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:34153:31)
      at tryNodeResolve (file:///Users/re/IdeaProjects/first-it/frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:33842:20)
      at Context.resolveId (file:///Users/re/IdeaProjects/first-it/frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:33602:28)
      at async Object.resolveId (file:///Users/re/IdeaProjects/first-it/frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40462:32)
      at async TransformContext.resolve (file:///Users/re/IdeaProjects/first-it/frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40227:23)
      at async normalizeUrl (file:///Users/re/IdeaProjects/first-it/frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:37137:34)
      at async TransformContext.transform (file:///Users/re/IdeaProjects/first-it/frontend/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:37278:47)
```

**Comment by ddmy** [comment]
`
[Vue warn]: useCssVars is called without current active component instance.
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
[Vue warn]: Invalid VNode type: Symbol(Fragment) (symbol) 
`
这个问题是因为`vue3-gantt`所依赖的vue版本与你当前项目所使用的vue版本不一致。
简单的解决办法是在安装最新版本`vue3-gannt`后，删除 `node_modules/vue3-gantt/node_modules` 目录 @re-ovo

**Comment by ddmy** [comment]
> `[Vue warn]: useCssVars is called without current active component instance. [Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. [Vue warn]: Invalid VNode type: Symbol(Fragment) (symbol) ` 这个问题是因为`vue3-gantt`所依赖的vue版本与你当前项目所使用的vue版本不一致。 简单的解决办法是在安装最新版本`vue3-gannt`后，删除 `node_modules/vue3-gantt/node_modules` 目录 @re-ovo

@re-ovo  已解决 #13
